[[redirects]]
  from = "/minilyrics-proxy/"
  to = "http://bzeutzheim.de:8981"
  status = 200
  force = true

[[redirects]]
  from = "/minilyrics/*"
  to = "http://search.crintsoft.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.spotify-karaoke.netlify.app/"
  to = "https://spotify-karaoke.netlify.app/"
  status = 301

[[redirects]]
  from = "/assets/*"
  to = "/en/assets/:splat"
  status = 200

[[redirects]]
  from = "/pl/*/"
  to = "/pl/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/pl/index.html"
  status = 200
  conditions = {Language = ["pl"]}

[[redirects]]
  from = "/*"
  to = "/en/index.html"
  status = 200
